### ISSUE TITLE
표 너비 불량

### ISSUE THREAD

**Issue by centrair-hoya** [LiteHell/theseed-skin-buma#28]
https://screenshots.firefox.com/cj8LGN5Tr3Rq2GV2/namu.wiki
https://screenshots.firefox.com/dCaWZDC6jMlXn3UH/namu.wiki

너비 미지정시 기본 100% 적용됨. senkawa와 상이한 부분이니 고치는 것이 옳은 것으로 보임.

**Comment by PlavorSeol** [comment]
```css
.content table
{width: initial;}
```
